pr:
  branches:
    include:
    - main
  paths:
    include:
    - eng/PR/Sweetener.Extensions.Options.ConfigurationExtensions.yml
    - eng/PR/Templates/*
    - eng/Scripts/*
    - eng/Templates/*
    - src/AssemblyInfo.Common.cs
    - src/Directory.Build.props
    - src/Directory.Build.targets
    - src/Extensions/Sweetener.Extensions.sln
    - src/Extensions/Sweetener.Extensions.Options.ConfigurationExtensions/*
trigger: none

jobs:
- template: ../Templates/Jobs.yml
  parameters:
    project: 'Sweetener.Extensions.Options.ConfigurationExtensions'
    type: 'Extensions'
